# Generated by Django 5.0 on 2024-02-25 07:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_tracker", "0002_alter_task_assignor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="request",
            unique_together={("member", "task")},
        ),
    ]
