# Generated by Django 5.0 on 2024-02-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_tracker", "0007_alter_task_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="start at"),
        ),
    ]
